### ISSUE TITLE
Karabiner-Elements crash

### ISSUE THREAD

**Issue by mox418** [tekezo/Karabiner-Elements#99] opened 2016-09-22 14:56 UTC
Hi,

My Karabiner-Elements crashed whenever I launched it (an "Internal Error" windows prompted). It was working initially but after I download the karabiner.json example and made some changes, then it crashed. I tried uninstalled, reinstalled and deleted the json file but nothing works.

One question, in order to have the keyboard mapping work, do I need to uninstall the original "Karabiner"? Do I need to open "Karabiner-Elements" everytime (which I cant open now)?

Please help.

**Comment by a-triant** [comment] 2016-09-22 15:14
Duplicate of #69 

Try deleting the log file, execute this command in the Terminal.app:
`rm ~/.karabiner.d/log/console_user_server_log.txt`

**Comment by mox418** [comment] 2016-09-23 02:03
Hi a-triant, thanks. It solved the problem.

However, I still not getting the key mapping to works, below is the content of my karabiner.json:

{
    "profiles": {
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_control": "left_command”,
		"left_command”: "left_control”,
		“right_command”: “Home”,
		“right_option”: “end”
            }
        }
    }
}

**Comment by mox418** [comment] 2016-09-27 02:06
Hi anyone can help? I still don't get my key mapping to work :-(

do I need to uninstall the original "Karabiner"? Do I need to open "Karabiner-Elements" everytime (which I cant open now)?

**Comment by talha131** [comment] 2016-09-27 08:10
@mox418 First delete your configuration file. Second use a code editor like Atom or Visual Studio Code or TextMate to edit your configuration.

Copy and paste following content

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                        "left_control": "left_command",
                        "left_command": "left_control",
                        "right_command": "home",
                        "right_option": "end"
            }
        }
    ]
}
```

**Comment by mox418** [comment] 2016-09-27 08:34
@talha131 thanks. it works.

**Closed** 2016-09-27 13:58 UTC
