### ISSUE TITLE
Capslock to Esc on key up, Ctrl otherwise

### ISSUE THREAD

**Issue by 3rd3** [tekezo/Karabiner-Elements#193] opened 2016-09-29 13:38 UTC
Is it possible to map caps lock to escape on the key up event if no other key is pressed at the same time and to control otherwise?

**Comment by trsk** [comment] 2016-09-29 14:13
Would be great when combined with Hyper!

**Comment by talha131** [comment] 2016-09-29 14:20
Related to #8

**Comment by atomkirk** [comment] 2016-09-29 14:40
This is exactly the same as #8. I suggest closing this issue.

**Comment by 3rd3** [comment] 2016-09-29 16:04
It's similar, but not the same.

**Comment by atomkirk** [comment] 2016-09-29 16:23
It's exactly the same. The example he gives is `Control_L to Control_L (+when you type Control_L only, send Escape)` You map Control_L to your caps lock on Mac using "Modifier Keys…" in keyboard preferences. That issue asks for a general feature that solves this exact use case.

**Comment by 3rd3** [comment] 2016-09-29 17:07
In #8, the distinctions is made based on a timeout. In my issues it is based on the key up event.

**Comment by adhipg** [comment] 2016-09-29 17:30
Duplicate of #18

**Closed** 2016-09-29 21:18 UTC
