### ISSUE TITLE
My bluetooth logitech mouse(MX Anywhere2) is not working.

### ISSUE THREAD

**Issue by xolidon** [tekezo/Karabiner-Elements#84] opened 2016-09-22 07:50 UTC
My bluetooth logitech mouse(MX Anywhere2) is not working.
Setting problems?

**Comment by davidrothera** [comment] 2016-09-22 09:07
Seeing the same but with the MX Master (very similar) where as soon as I open KE the mouse stops responding until I quit the app 👎

**Comment by Punksmurf** [comment] 2016-09-22 10:22
Logitech's support voor Sierra is pretty bad at the moment. This does not seem to be a problem with Karabiner Elements, though it seemed so at first. It keeps crashing or making my mouse act weird wether Elements is running or not, though starting Elements definitely didn't help. In one instance the Elements window became "glued" to my mouse cursor. However, I also had a non-responding mouse without running Elements. It's all a bit unclear.

First I uninstalled the Unifying software, which keeps crashing (at least it did for me): http://support.logitech.com/en_us/article/26976?product=a0qi00000069ufTAAQ. That helped a lot and I could use my mouse without problems. The Logitech Options software keeps working and recognising my MX Master, which is connected through a unifying dongle. As far as I understand it, you only need that software if you want to bind a new unifying dongle to your mouse.

**However** I cannot use my mouse over bluetooth anymore. I do not know if this is because I uninstalled the LLC package or because Logitech isn't yet ready for Sierra. Fact is that the latest download only mentions support up to MacOS 10.11 (Sierra is 12).

**Comment by Punksmurf** [comment] 2016-09-22 10:27
Update, after replying I noticed quite a few Karabiner processes running which I didn't realise were running. After quitting those, my mouse started working again. It's all a bit weird though, seeing as it *did* work when using the unifying connector but *not* over bluetooth. So there's probably some weird interplay between Logitech and Karabiner / Karabiner-Elements.

**Comment by davidrothera** [comment] 2016-09-22 10:28
I should note that my MX Master is connected via Bluetooth and I only have the Options software installed.

**Comment by digitalstep** [comment] 2016-09-22 13:17
Similar here. Mouse stops working as soon as karabiner is started.
Quitting karabiner makes the mouse work again.
Connection via BT or unifying dongle makes no difference, I tried both.
Removing Logitech Unifying something and Logitech Options helped, although a reboot was required. 
Reinstalling Logitech Options afterwards, and everything is working smoothly.

**Comment by bvankuik** [comment] 2016-09-22 17:04
I bet these mice also identify as a keyboard, not just as a mouse.

**Comment by Kwpolska** [comment] 2016-09-23 15:59
I have the same issue with Microsoft Sculpt Comfort Mouse, which also claims it’s a keyboard (just so it can press the Windows key). Whenever I launch Karabiner-Elements, the mouse is disabled; closing Karabiner fixes it.

```
[2016-09-23 17:53:03.441] [grabber] [info] matching device: manufacturer:, product:Microsoft Sculpt Comfort Mouse, vendor_id:0x45e, product_id:0x7a2, location_id:0x5e01f3df, serial_number:c0-33-5e-01-f3-df registry_entry_id:4294968532 @ void device_grabber::device_matching_callback(IOHIDDeviceRef _Nonnull)

**Comment by lacyjpr** [comment] 2016-09-24 00:43
I have the same issue with a Logitech m535 bluetooth mouse: As soon as I launch Karabiner-Elements, the mouse is disabled, closing Karabiner-Elements makes the mouse work again.

**Comment by gamesbrainiac** [comment] 2016-09-24 01:02
Same issue here. Also, it appears that on the MX Master, the espose button seems to work, but it turns into the magnify command, which is sorta weird.

**Comment by morphix9** [comment] 2016-09-25 08:07
Having the same problems. Any solution?

**Comment by Paik4Life** [comment] 2016-09-25 12:57
Yeah, I ran into all sorts of problems when installing Karabiner Elements. My MX Master wouldn't work and I couldn't do basic keyboard shortcuts like Comm+Opt+Esc. I wasn't able to kill the processes until I uninstalled the apps and removed the Application Support files. It was only after all that that I could get normal functionality back. Looking forward to an update. I basically only use this tool for remapping the Caps Lock key, but it feels awful not having that!

~Paik

**Comment by SpaceK33z** [comment] 2016-09-26 14:35
It looks like this has been fixed in version 0.90.41, with commit 2a769ddda075b50cd742ca9593cafd6f3fcbf18d. I also had this problem before (MX Master), and it works now :).

**Comment by xolidon** [comment] 2016-09-27 00:57
My mouse works good in version 0.90.41+ !!

**Comment by tekezo** [comment] 2016-09-29 03:37
I've changed the approach in v0.90.45.
Please confirm this issue also fixed in v0.90.45.

**Comment by tekezo** [comment] 2016-09-29 03:40
Related: #161

**Comment by lacyjpr** [comment] 2016-09-29 08:04
Updated to v0.90.45. Scroll wheel on Logitech m535 is no longer working. Was working in .90.44

**Comment by xolidon** [comment] 2016-09-30 01:33
The same here. Wheel doesn't work, but pointer works.
Logitech MX Anywhere2 via Bluetooth.

**Comment by luisfontes** [comment] 2016-10-03 19:16
Updated to v0.90.46 and my mouse (bluetotooth, mx2) stopped working. In v0.90.45 it was kind of working… If I quit KE the mouse goes backs to normal.

**Comment by cgrinds** [comment] 2016-10-08 23:18
With v0.0.47 bluetooth mouse is working again

**Comment by lacyjpr** [comment] 2016-10-09 20:40
Updated to v0.90.47 & Logitech m535 (bluetooth) is no longer working. Pointer doesn't move when Karabiner Elements is running. It works with version 0.90.44.

**Comment by DHaacke** [comment] 2016-10-10 15:45
I can confirm v0.90.47 is not working with the Logitech MX Master (bluetooth or unifying) and MacOS Sierra. Pointer is frozen, but MacBook Pro Retina trackPad works.

**Comment by DHaacke** [comment] 2016-10-10 16:30
Minutes after posting my previous comment, I got a notification that Logitech Option 6.30.48 was available, and now Elements v0.90.47 seems to be working.

**Comment by khmyznikov** [comment] 2016-10-24 10:53
Elements 0.90.55 , Logitech 6.30.48, Mouse M535 doesn't work

**Comment by tekezo** [comment] 2016-10-27 02:47
Thank you for feedbacks!
I added Devices tab in Karabiner-Elements Preferences which allows you to ignore specific devices and ignore the keyboard-and-mouse combined device in default.
Please upgrade to the latest version and check the Devices tab in Preferences.

**Comment by lacyjpr** [comment] 2016-10-27 05:16
With Karabiner-Elements 0.90.58 Logitech M535 Bluetooth mouse is working: 
When it installed, it automatically ignored the bluetooth mouse. If I check the Bluetooth mouse button, it stops working. If I uncheck and ignore the mouse, all is good!

**Comment by cgrinds** [comment] 2016-10-27 12:47
Same as @lacyjpr, 0.90.58 now works with MX Master. Thanks!

**Closed** 2016-10-27 14:49 UTC

**Comment by Kwpolska** [comment] 2016-10-31 09:55
Could there be a way to make mouse+keyboard devices work? I want to remap my mouse’s Windows (left_command) key to something more useful. Enabling the mouse in Karabiner disables the mouse part.

```
[2016-10-31 10:47:51.208] [info] [grabber] version 0.90.61
[2016-10-31 10:47:52.186] [info] [grabber] matching device:
[2016-10-31 10:47:52.204] [info] [grabber]   manufacturer: 
[2016-10-31 10:47:52.205] [info] [grabber]   product: Microsoft Sculpt Comfort Mouse
[2016-10-31 10:47:52.205] [info] [grabber]   vendor_id: 0x45e
[2016-10-31 10:47:52.205] [info] [grabber]   product_id: 0x7a2
[2016-10-31 10:47:52.205] [info] [grabber]   location_id: 0x5e01f3df
[2016-10-31 10:47:52.206] [info] [grabber]   serial_number: c0-33-5e-01-f3-df
[2016-10-31 10:47:52.210] [info] [grabber]   registry_entry_id: 4294970031
[2016-10-31 10:47:52.222] [info] [grabber] IOServiceOpen is succeeded @ void virtual_hid_manager_client::matched_callback(io_iterator_t)
```

**Comment by bvankuik** [comment] 2016-10-31 10:00
If you just want to reconfigure the mouse button, couldn't you use something like BetterTouchTool? https://www.boastr.net/

**Comment by Kwpolska** [comment] 2016-10-31 10:03
Can BetterTouchTool remap a left_command event from the mouse device (but not the keyboard!) to something like ⌘Space?
