### ISSUE TITLE
Combine keys

### ISSUE THREAD

**Issue by slovenianGooner** [tekezo/Karabiner-Elements#471] opened 2016-12-06 11:05 UTC
Hi,

is it possible to do something like:

Option_R (AltGr) + 1 = ~
or 
Option_R (AltGr) + Q = \

So, basically what used to be a set of rules for standard Windows/Linux style keyboards.

**Comment by FuegoFro** [comment] 2016-12-14 22:47
Seems like a dupe of https://github.com/tekezo/Karabiner-Elements/issues/16?

**Comment by slovenianGooner** [comment] 2016-12-15 08:21
Seems like it, will close.

**Closed** 2016-12-15 08:21 UTC
