### ISSUE TITLE
Built-in and external keyboard differs

### ISSUE THREAD

**Issue by jyggen** [tekezo/Karabiner-Elements#229] opened 2016-10-03 23:12 UTC
Both my built-in and external keyboard are using a Swedish layout:

![Keyboard](https://i.imgur.com/szp3eSM.png)

Depending on whether I use my built-in or the external keyboard the `<` key (red)  and `§` key (blue) outputs different characters. Basically it's like `<` and `§` switch places when I use the external keyboard.

Key | Expected | Built-in | External
--- | -------- | -------- | --------
< | < | < | §
L Shift + < | > | > | °
L Alt + < | ≤ | ≤ | ¶
§ | § | § | <
L Shift + § | ° | ° | >
L Alt + § | ¶ | ¶ | ≤

These are the only two keys I've noticed having this weird behaviour.

**Comment by sicher** [comment] 2016-10-04 07:07
I noticed the same, also on Swedish layout. This is maybe why the keyboard detection in macOS does not work. Clicking "Change Keyboard Type" in the keyboard preferences and then pressing the key immediately to the right of left shift does not identify the keyboard.

**Comment by maru3l** [comment] 2016-10-06 14:33
getting the same issue with a french canadien keyboard

**Comment by mafredri** [comment] 2016-10-08 16:53
I just closed my issue (#269) as a duplicate of this one, however, in my case the internal MacBook keyboard has the wrong layout, i.e. not the expected result, whereas the external keyboard has the correct (expected) layout.

**Comment by mafredri** [comment] 2016-10-13 07:17
Hmm, not sure if I was mistaken originally or if my issue has changed, but currently the problem is exactly as jyggen describes it, the internal keyboard has the correct keymap and external has the non-expected keymap.

**Comment by gjherbiet** [comment] 2016-10-25 06:14
I can confirm that I face the exact same problem with the French (FR_fr) keyboard.
The affected keys are the same, but the characters differ :
- @/# for the blue key in @jyggen's screenshot
- </> for the red key

I have to enable the following swapping with an external keyboard and disable it when using the internal keyboard (that has the correct keymap).

![screen shot 2016-10-25 at 08 12 00](https://cloud.githubusercontent.com/assets/210227/19674823/fc2b5ade-9a8a-11e6-9ddc-3c029fbdbb73.png)

**Comment by tekezo** [comment] 2016-10-28 17:12
Please upgrade Karabiner-Elements to the latest version and then set keyboard type in Devices tab.
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#set-keyboard-type

**Closed by tekezo** 2016-10-28 17:12 UTC

**Comment by jyggen** [comment] 2016-11-02 10:18
No matter which keyboard type I set my external keyboard the blue key remains mapped to the red key (and vice versa).

If I set up modifiers to map blue to red and red to blue (basically what's described under "Swapping Section/Paragraph § key on non-US keyboards" in the readme) it's working just fine, but then my internal keyboard gets the problem instead.

**Comment by gjherbiet** [comment] 2016-11-02 10:25
I confim that I still have the same problem, whatever settings I pick for keyboard type.
I tried restarting after upgrade and Karabiner-Elements update (to 0.90.61) and the problem persists.

I use two keyboards with French layout (MacBookPro12,1 internal keyboard and Apple wired aluminium keyboard). They are both set to "ISO" but:
- the internal keyboard is OK ;
- the external Aluminium keyboard still has keys swapped (and I have to add the two rules mentioned in a previous comment.

![screen shot 2016-11-02 at 11 21 51](https://cloud.githubusercontent.com/assets/210227/19925123/f7f693ec-a0ee-11e6-8e82-e08b0cd57b80.png)

So it seems the merged pull request unfortunately doesn't have any impact on used keyboard type.

**Comment by RobTS** [comment] 2016-11-06 11:17
Also still having problems after latest upgrade, changing Keyboard Type didn't change a thing.

**Comment by jthebert** [comment] 2016-11-07 20:06
I am having the same problem with a frenck keyboard as mentionned by  @gjherbiet  
* the internal keyboard is OK ;
* the external Aluminium keyboard still has keys swapped

**Comment by nvulchev1** [comment] 2016-11-14 11:52
I also have the same issue with Karabiner-Elements 0.90.64. Again with configuration https://cloud.githubusercontent.com/assets/210227/19674823/fc2b5ade-9a8a-11e6-9ddc-3c029fbdbb73.png

**Comment by gjherbiet** [comment] 2016-12-12 14:45
Please, is it possible to re-open this issue.
I have updated to 0.90.68 and the problem is still there.

With the aforementioned setup (i.e ISO type "forced" on both keyboards), "@" and ">" are still swapped on the external Aluminium keyboard and not on the built-in keyboard.
Both keyboard have French layout.

This is the information about my MacBook pro:
![screen shot 2016-12-12 at 15 44 18](https://cloud.githubusercontent.com/assets/210227/21103230/dfc5a7c4-c081-11e6-8308-86a62086c564.png)

This issue is impairing many users w/o English keyboard. This is really annoying and some consideration would be appreciated.

Thanks in advance.

**Comment by jannewaren** [comment] 2016-12-16 05:20
+1 for this. Could you reopen? I have the latest Karabineri-Elements and setting the keyboard type has no effect.

Loving Karabineri-Elements and successfully mapping some special keys (caps-lock) with it! A big thanks to anyone contributing to it :) It's great that I was finally able to update to macOS Sierra..

But.. I have the same problem, and as a developer it's not a small one, I need these keys all the time. So the "<>" and "§°" keys displayed in blue and red in the original issue message, are swapped. So internal keyboard works fine, but the external one (wired apple keyboard, Finnish layout) are swapped.

MacBook Pro 13" Mid 2014
macOS Sierra 10.12.2

Is there a way around this? There's no option to even map these keys in Karabineri-Elements??

**Comment by nicmar** [comment] 2017-02-01 07:22
I just updated to the latest version (0.90.84), and I changed in Virtual Keyboard > Keyboard type > from ANSI to ISO, and now <> §° works correctly!

**Comment by jannewaren** [comment] 2017-02-02 09:54
I can confirm this worked, the external Apple USB keyboard now handles <> §° correctly. But this changed the problem to be with the integrated MacBook Pro keyboard. Now that mixes up these same two buttons 😢

**Comment by nicmar** [comment] 2017-02-02 10:01
Darn, you are right, i didn't try that. Guess I'll have to quit karabiner when I'm on the Macbook then. I only need it when connected.

**Comment by nicmar** [comment] 2017-02-02 10:06
i also noticed that F1/F2 to change brightness of the screen (LG Ultrafine 5K) doesn't work with Karabiner Elements running. However F14/F15 does, which also works without KE.

**Comment by ruiramos** [comment] 2017-09-19 07:39
+1. On a British keyboard layout the §± and `~ keys get swapped between external and internal keyboard. It seems that the external (Apple) keyboard needs the virtual keyboard type to be set do ISO and the internal one ANSI.

**Comment by krokofant** [comment] 2017-11-08 00:48
I'm having this issue on my internal Macbook keyboad with Swedish layout. Keyboard type is already specified as ISO.

**Comment by FellowMiner** [comment] 2017-11-15 10:55
Setting:
Karabiner-Elements: 11.3.0
My internal MBP keyboard with German layout is identified as ISO and set as such through the KeyboardSetupAssistant.app. My external Apple Pro Keyboard is also correctly identified and set as ISO through the assistant app.

Problem:
If I set Karabiner-Elements to ISO, the internal has swapped keys for ^ and < but external is fine. If I set it to ANSI, the internal is fine but the external is swapped.

**Comment by HobbinHood** [comment] 2017-11-15 10:56
Setting:
Karabiner-Elements: 11.3.0
My internal MBP keyboard with German layout is identified as ISO and set as such through the KeyboardSetupAssistant.app. My external Apple Pro Keyboard is also correctly identified and set as ISO through the assistant app.

Problem:
If I set Karabiner-Elements to ISO, the internal has swapped keys for ^ and < but external is fine. If I set it to ANSI, the internal is fine but the external is swapped.

**Comment by odi-um** [comment] 2017-11-22 12:42
same issue as described by @HobbinHood

**Comment by mb21** [comment] 2017-11-25 09:43
exact same problem as @HobbinHood with Karabiner-Elements: 11.3.0 on High Sierra 10.3.1 with Swiss German external Apple USB and internal MBP keyboard.

**Comment by emile-3d** [comment] 2017-11-29 22:39
Same here, Sierra 10.12.2 and Karabiner 11.3.0
I can't find a way to assign different  keyboard types to different keyboards (using 2 at a time)
I have an ANSI internal keyboard type with one kind of mapping, and I have an ISO external with another needs in mapping. 
Any thoughts?

**Comment by rspi** [comment] 2018-02-01 14:38
I have the same issue. But for me.. not even changing the virtual keyboard layout helps..

**Comment by rkrz** [comment] 2018-02-01 14:54
I have tried several thing to resolve this issue, so I'm not entirely sure if this is the actual solution. At least it works for me now.

I resetted the 'Know keyboards' on macos, so when connecting an external keyboard the 'Keyboard Setup Assistant' is shown again. Check out this article:
https://www.techwalla.com/articles/how-to-reset-the-external-keyboard-on-an-apple-mac

**Comment by gstn-caruso** [comment] 2018-04-18 22:39
Today I've just updated to the version 12.0.0 and this issue is happening to me again. I have the ansi layout, but karabiner is detecting it as iso.

**Comment by mb21** [comment] 2018-04-19 07:29
I wonder whether we should just create a new issue since nobody seems to be reading this...

**Comment by nicmar** [comment] 2018-04-19 07:55
I got the same issue, but since I don't use §° (keys above tab), I remapped them to <>, which in turn made <> work, instead of hitting the §° keys (Swedish keyboard). However they seem to work now, so I don't know if it was on another profile, since I'm switching between laptop and a Microsoft Ergo 4000.

**Comment by reimertz** [comment] 2018-04-19 11:39
I'm on a Swedish keyboard and this solved it for me, remapping `non_us_backslash` to `grave_accent_and_tilde`.

![image](https://user-images.githubusercontent.com/625287/38989317-b5186032-43d6-11e8-9c20-42fbe0aac22e.png)

**Comment by alien0matic** [comment] 2018-09-13 14:19
Having the exakt same problem with a german MacBook and german keyboard. Reimertz tip helped me fix this, but it's a shame I have to fix it.

**Comment by fjeddy** [comment] 2019-02-25 17:37
Same issue here. Why did you close this @tekezo, it's clearly not fixed. And three years later it's still an issue.

**Comment by adstek** [comment] 2019-03-16 17:03
just started using Karabiner, I have the problem too. MacOS 10.13.6 and Karabiner 12.2

**Comment by ksuuk** [comment] 2021-01-26 13:28
@reimertz 

Hack works for <> but then I loose combinantion right alt <> key ( which gives pipe |) usage in Microsoft Remote Desktop Beta > Linux > cli. How to fix it?

**Comment by themightyoarfish** [comment] 2021-06-28 09:32
I have this problem with 13.5 with a 2019 macbook pro and a Microsoft sculpt usb keyboard.

**Comment by rauerhans** [comment] 2021-12-02 09:25
Same problem with the CTRL Keyboard, US layout and a Macbook with German layout. Option and Cmd Keys are switched.

**Comment by kodmanyagha** [comment] 2022-09-13 21:52
I'm using Turkish Q default layout external keyboard and this settings is fine now.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/3948692/190015848-6b6febbc-19df-426a-8fbe-979f7a7750a4.png">
