### ISSUE TITLE
Incompatibility with Zoom function of the Accessibility.

### ISSUE THREAD

**Issue by yositomi-opu** [tekezo/Karabiner-Elements#372] opened 2016-10-29 22:17 UTC
Before upgrading to Sierra, I used Zoom function via Ctrl+Scroll function, but on Sierra and Karabiner-Elements, Zooming does not work well. In some case, it works with any of None/Ctrl/Option/Cmd plus Scroll function, but in other cases, it does not work any more.
For example, when I changed the modifier key for Zooming to 'Option', it did work with only scroll function, so I could not use actual scroll function on the browser etc. If quit the Karabiner-Elements, then I can use the Zooming function correctly. But I could not reproduce this phenomena again.
I use JIS keyboard and formerly used Karabiner with the setting 'use japanese keyboard as us keyboard'.
My karabiner.json is as follows:
{
    "profiles": [
        {
            "devices": [
                {
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 626,
                        "vendor_id": 1452
                    },
                    "ignore": false,
                    "keyboard_type": 0
                }
            ],
            "fn_function_keys": {
                "f1": "vk_consumer_brightness_down",
                "f10": "mute",
                "f11": "volume_down",
                "f12": "volume_up",
                "f2": "vk_consumer_brightness_up",
                "f3": "vk_mission_control",
                "f4": "vk_launchpad",
                "f5": "vk_consumer_illumination_down",
                "f6": "vk_consumer_illumination_up",
                "f7": "vk_consumer_previous",
                "f8": "vk_consumer_play",
                "f9": "vk_consumer_next"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "grave_accent_and_tilde": "backslash",
                "international1": "grave_accent_and_tilde"
            }
        }
    ]
}
 
I would appreciate this is helpful for the improvement.

**Comment by kunichiko** [comment] 2016-10-30 03:40
I think this is a duplicate of #111 and #288.

**Closed** 2016-10-30 22:06 UTC

**Comment by entonio** [comment] 2016-11-21 11:48
See https://github.com/tekezo/Karabiner-Elements/issues/89
