### ISSUE TITLE
Version 12 breaks simultaneous behavior

### ISSUE THREAD

**Issue by pokey** [tekezo/Karabiner-Elements#1345] opened 2018-04-13 10:16 UTC
I see in the release notes for version 12:

> Changed `simultaneous` behaviour to post key_up events when any key is released.

This is problematic for me, because I found the old behavior to be great.  For example, I had the following:

```json
{
    "description": "V+J as ctrl",
    "from": {
        "simultaneous": [
            {"key_code": "v"},
            {"key_code": "j"}
        ],
        "modifiers": {"optional": ["any"]}
    },
    "to": [
        {
            "key_code": "left_control",
            "lazy": true
        }
    ],
    "type": "basic"
}
```

With the old behavior, I could press `V+J`, release `V`, and then press `F` or `B` as many times as I wanted to scroll up and down in Vim.

Would it be possible to introduce a flag that reenables the old behavior?

(and of course, thank you so much for this software; I could not live without it)

**Comment by tekezo** [comment] 2018-04-14 11:38
Thank you for feedback!

I've added simultaneous_options.key_up_when at v12.0.1.

Upgrade to the latest beta version.
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

Then add `simultaneous_options` as follows.

```
{
    "description": "V+J as ctrl",
    "from": {
        "modifiers": {
            "optional": [
                "any"
            ]
        },
        "simultaneous": [
            {
                "key_code": "v"
            },
            {
                "key_code": "j"
            }
        ],
        "simultaneous_options": {
            "key_up_when": "all"
        }
    },
    "to": [
        {
            "key_code": "left_control",
            "lazy": true
        }
    ],
    "type": "basic"
}
```

**Comment by pokey** [comment] 2018-04-14 12:36
Wow!  I've never seen that quick a turnaround from feature request => fix => release for any open source project.  You're the man!!

Just tested it out and it works like a charm.  Thanks!

**Comment by fedde-s** [comment] 2018-04-16 12:37
Ah, might issue #1353 which I just typed out one key at a time be a duplicate of this? Should I try the beta button?

**Comment by fedde-s** [comment] 2018-04-16 12:43
No, never mind, my issue is not resolved in the beta.

**Closed** 2018-04-16 14:06 UTC
