### ISSUE TITLE
Regular funktion key setting no more working 0.90.58 (Sierra 10.12.1)

### ISSUE THREAD

**Issue by ZeeArts** [tekezo/Karabiner-Elements#353] opened 2016-10-27 05:55 UTC
In system preferences i set F-Keys as regular function keys (which is only shown if i connect my BT Apple Keyboard). But since last update (0.90.58) Karabiner-Elements ignore this setting. In Karabiner-Elements i modified "scroll lock" to "Fn-Key". With 0.90.58 i have regular function Keys only if i press my binded Fn-Key. If i go back to 0.90.55 it's working normal.

**Comment by tekezo** [comment] 2016-10-27 07:10
If you are using keyboard-and-mouse combined device, Karabiner-Elements ignore them in default.
Please check Devices tab in Preferences.

**Comment by kron4eg** [comment] 2016-10-27 09:14
@tekezo what you are saying is to uncheck "apple internal keyboard / trackpad" in devices?
In that case the system stops to see my capslock remap (I've remapped it as f18). 

If I do check "apple internal keyboard / trackpad" in devices, then all my functional keys start to work according "functional keys" in karabiner tab... Unfortunately in this case fn+Fkeys combination cease to work properly.

So what I'm saying is that "functional keys" from karabiner-elements and system setting "keyboard -> Use all F1, F2, etc. keys as standard function keys" are conflicting with each other.

**Comment by akaspin** [comment] 2016-10-27 09:45
Confirmed.

**Comment by digitaldreamer** [comment] 2016-10-27 15:26
My standard setup is simple, I just remap `caps-lock` to `esc` and that's it.

I use `system preferences -> keyboard -> Use all F1, F2, etc. keys as standard function keys`

![image](https://cloud.githubusercontent.com/assets/82082/19773046/23786d5a-9c36-11e6-9984-3d0c52c6fa55.png)

However with this set karabiner overrides the `function keys` on my mac to be the mac special keys.

If I remap the function keys in karabiner to the corresponding function keys returns the function keys to their normal mapping HOWEVER the `fn` key has no effect and I cannot press `fn + f10` to mute sound. This was working in the previous version.

![image](https://cloud.githubusercontent.com/assets/82082/19773566/0d53d6fc-9c38-11e6-9ce6-6e5f918ebe2c.png)

**Comment by digitaldreamer** [comment] 2016-10-27 15:32
@tekezo I don't want to simply turn off karabiner for an input device because I still want it to remap keys in `Simple Modifications`. I do not want karabiner to do anything with the `Function Keys` which it seems impossible to do.

@akaspin This returns the function keys to their default state however I still cannot get the `fn` modifier combo to work with karabiner applied.

**Comment by kron4eg** [comment] 2016-10-27 15:34
@digitaldreamer BTW, latest release 10.12.1 allow to map caps lock to esc without external tools :)

**Comment by digitaldreamer** [comment] 2016-10-27 15:35
@kron4eg nice! I'll take a look, seems like a simpler option overall. Thanks for the heads up.

**Comment by kron4eg** [comment] 2016-10-27 15:39
@digitaldreamer Like this: <img width="445" alt="screenshot 2016-10-27 18 36 39" src="https://cloud.githubusercontent.com/assets/30984/19774023/5f71522a-9c74-11e6-9e05-99164bd25c02.png">

But away from this special case (since in resolved by OS), your point is totally valid, karabiner started to interference with function keys and doesn't take Fn button into account :(

**Comment by digitaldreamer** [comment] 2016-10-27 15:42
@kron4eg 

Yes, for my use-case it appears I do not need karabiner. However, I feel the `fn` button interference is an issue other people would be interested in solving. Thanks!

**Comment by todofixthis** [comment] 2016-10-27 15:57
On my system, this functionality was working correctly until I installed updates this morning:

- macOS Sierra:  10.12.0 -> 10.12.1
- Karabiner-Element:  0.90.53 -> 0.90.58

I did a quick glance over the [diff between 0.90.53 and 0.90.58](https://github.com/tekezo/Karabiner-Elements/compare/4d0362ae46f18e61b7e719e2c7fe4fb6cf60bd8b...fe40297319d0690cfc84a592885f2f9580c4acb0) and I didn't see anything that looked related to this issue, so my suspicion is that the regression was caused by the macOS update.

Using built-in trackpad on a MacBook Pro, no external devices connected.

**Comment by tekezo** [comment] 2016-10-27 16:29
Thank you for feedback!
Karabiner-Elements v0.90.58 has an issue that ignores "Use all F1, F2, etc. keys as standard function keys" setting in System Preferences.

I've fixed this issue in v0.90.59.
Please upgrade to the latest version.

**Closed by tekezo** 2016-10-27 16:29 UTC

**Comment by todofixthis** [comment] 2016-10-27 18:05
Confirmed fixed in 0.90.59.

**Comment by kron4eg** [comment] 2016-10-28 10:25
@tekezo thank you very much! works as expected now 👍
