### ISSUE TITLE
10.12.2 Beta: Enabled keyboards become non-responsive

### ISSUE THREAD

**Issue by chorn** [tekezo/Karabiner-Elements#413] opened 2016-11-07 20:19 UTC
On the 10.12.2 Beta, any enabled keyboards become non-responsive.

This doesn't count as a bug since 10.12.2 is still beta! I wanted to warn anyone watching that avoiding it is a good idea if they want Karabiner-Elements to work.

**Comment by tphalp** [comment] 2016-11-08 03:20
Duplicate of #383, possibly.

**Comment by saagarjha** [comment] 2016-11-09 17:29
@chorn This appears to be fixed in the latest beta (16C41b).

**Comment by IamHokum** [comment] 2016-11-10 09:58
I now have this same issue with v0.90.64 after upgrading from v0.90.47.

**Closed** 2016-11-13 15:59 UTC
